packages:
  - packages/*
  - apps/*

catalog:
  '@prettier/plugin-oxc': 0.2.3
  '@csstools/css-tokenizer': 4.0.2
  '@jridgewell/trace-mapping': 0.3.31
  '@playwright/test': 1.63.0
  '@types/node': 24.13.5
  csstype: 3.2.3
  html-element-attributes: 3.5.0
  oxlint: 1.86.0
  prettier: 3.9.9
  property-information: 7.2.0
  sirv: 3.0.2
  smol-toml: 1.9.0
  typescript: 7.1.0-dev.20261005.1
  vite: 8.3.1
  vitest: 5.0.3
  vscode-jsonrpc: 9.0.3

autoInstallPeers: false

onlyBuiltDependencies: []
